function test(){
	if($("#cpname").val()==""){
		alert("产品名称不能为空");
		$("#cpname").focus();
	}else{
		if($("#type").val()==""){
			alert("规格型号不能为空");
			$("#type").focus();
		}else{
			if($("#wtcompany").val()==""){
				alert("委托单位不能为空");
				$("#wtcompany").focus();
			}else{
				if($("#lxr").val()==""){
					alert("联系人不能为空");
					$("#lxr").focus();
				}else{
					if($("#sccompany").val()==""){
						alert("生产单位不能为空");
						$("#sccompany").focus();
					}else{
						if($("#tel").val()==""){
							alert("联系电话不能为空");
							$("#tel").focus();
						}else{
							if($("#cpcode").val()==""){
								alert("产品编号不能为空");
								$("#cpcode").focus();
							}else{
								if($("#wtdate").val()==""){
									alert("委托日期不能为空");
									$("#wtdate").focus();
								}else{
									if($("#address").val()==""){
										alert("单位地址不能为空");
										$("#address").focus();
									}else{
										if($("#wtcheck").val()==""){
											alert("委托检验要求不能为空");
											$("#wtcheck").focus();
										}else{
											if($("#checkyj").val()==""){
												alert("检验依据不能为空");
												$("#checkyj").focus();
											}else{
												if($("#checkmoney").val()==""){
													alert("检验费用不能为空");
													$("#checkmoney").focus();
												}else{
													if($("#wcdate").val()==""){
														alert("要求完成日期不能为空");
														$("#wcdate").focus();
													}else{
														if($("#phproject").val()==""){
															alert("需委托单位配合完成的项目不能为空");
															$("#phproject").focus();
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
