function test(){
	if($("#wtcompany").val()==""){
		alert("委托单位不能为空");
		$("#wtcompany").focus();
	}else{
		if($("#ypname").val()==""){
			alert("样品名称不能为空");
			$("#ypname").focus();
		}else{
			if($("#scstore").val()==""){
				alert("制造厂商不能为空");
				$("#scstore").focus();
			}else{
				if($("#type").val()==""){
					alert("型号/规格不能为空");
					$("#type").focus();
				}else{
					if($("#cccode").val()==""){
						alert("出厂编号不能为空");
						$("#cccode").focus();
					}else{
						if($("#jydate").val()==""){
							alert("接样日期不能为空");
							$("#jydate").focus();
						}else{
							if($("#checkyj").val()==""){
								alert("检验依据不能为空");
								$("#checkyj").focus();
							}else{
								if($("#checkend").val()==""){
									alert("检验结论不能为空");
									$("#checkend").focus();
								}
							}
						}
					}
				}
			}
		}
	}
}


