function test(){
	if($("#type").val()==""){
		alert("设备型号不能为空");
		$("#type").focus();
	}else{
		if($("#azcompany").val()==""){
			alert("安装单位不能为空");
			$("#azcompany").focus();
		}else{
			if($("#scstore").val()==""){
				alert("生产厂家不能为空");
				$("#scstore").focus();
			}else{
				if($("#tsjcode").val()==""){
					alert("提升机编号不能为空");
					$("#tsjcode").focus();
				}else{
					if($("#ioscode").val()==""){
						alert("安全生产许可证编号不能为空");
						$("#ioscode").focus();
					}else{
						if($("#aqscode").val()==""){
							alert("安全锁编号不能为空");
							$("#aqscode").focus();
						}else{
							if($("#ccdate").val()==""){
								alert("设备编号/出厂日期不能为空");
								$("#ccdate").focus();
							}else{
								if($("#ysnumber").val()==""){
									alert("验收数量不能为空");
									$("#ysnumber").focus();
								}
							}
						}
					}
				}
			}
		}
	}
}


