function test(){
	if($("#cpname").val()==""){
		alert("产品名称不能为空");
		$("#cpname").focus();
	}else{
		if($("#type").val()==""){
			alert("规格型号不能为空");
			$("#type").focus();
		}else{
			if($("#ypcode").val()==""){
				alert("样品编号不能为空");
				$("#ypcode").focus();
			}else{
				if($("#ypnumber").val()==""){
					alert("样品数量不能为空");
					$("#ypnumber").focus();
				}else{
					if($("#scdate").val()==""){
						alert("生产日期不能为空");
						$("#scdate").focus();
					}else{
						if($("#checktype").val()==""){
							alert("检验类别不能为空");
							$("#checktype").focus();
						}else{
							if($("#wtcompany").val()==""){
								alert("委托单位不能为空");
								$("#wtcompany").focus();
							}else{
								if($("#sccompany").val()==""){
									alert("生产单位不能为空");
									$("#sccompany").focus();
								}else{
									if($("#checkaddress").val()==""){
										alert("检验地点不能为空");
										$("#checkaddress").focus();
									}else{
										if($("#checktime").val()==""){
											alert("检验时间不能为空");
											$("#checktime").focus();
										}else{
											if($("#checkyj").val()==""){
												alert("检验依据不能为空");
												$("#checkyj").focus();
											}else{
												if($("#checkend").val()==""){
													alert("检验结论不能为空");
													$("#checkend").focus();
												}
												
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
