//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicationinfo
    {
        public string GUID { get; set; }
        public string userid { get; set; }
        public string applicompanyname { get; set; }
        public string applicompanyaddr { get; set; }
        public string applibusinessregistnumber { get; set; }
        public string appliorganizationcode { get; set; }
        public string appliregistercapital { get; set; }
        public string appliemployer { get; set; }
        public Nullable<System.DateTime> appliregistrationdate { get; set; }
        public string applieconomytype { get; set; }
        public string appliqualificationtypeid { get; set; }
        public string applilinkname { get; set; }
        public string applilinktel { get; set; }
        public string appliemail { get; set; }
        public string state { get; set; }
        public Nullable<bool> ispay { get; set; }
        public Nullable<System.DateTime> operatetime { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
    }
}
