//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class appraisalapplication
    {
        public string GUID { get; set; }
        public string userid { get; set; }
        public string appraisalcompanyname { get; set; }
        public string appraisalcompanyaddr { get; set; }
        public string appraisalgoodsname { get; set; }
        public string appraisalgoodstype { get; set; }
        public string appraisalmanufacturer { get; set; }
        public string appraisaloutfactorydate { get; set; }
        public string appraisalgoodssummary { get; set; }
        public Nullable<System.DateTime> appraisalplandate { get; set; }
        public Nullable<System.DateTime> appraisalapplicationdate { get; set; }
        public string appraisallinkname { get; set; }
        public string appraisallinktel { get; set; }
        public string appraisalemail { get; set; }
        public string state { get; set; }
        public Nullable<bool> ispay { get; set; }
        public Nullable<System.DateTime> operatetime { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
    }
}
