//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthPermission
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string HttpType { get; set; }
        public string Res { get; set; }
        public string PCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsShow { get; set; }
        public bool IsAvailable { get; set; }
        public string Operator { get; set; }
        public System.DateTime OperateTime { get; set; }
    }
}
