//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUser
    {
        public string UserName { get; set; }
        public string UserNo { get; set; }
        public string RealName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> IsInner { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string Remark { get; set; }
    }
}
