//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class expertsdesigninfo
    {
        public string GUID { get; set; }
        public string userid { get; set; }
        public string designcompanyname { get; set; }
        public string designcompanyaddr { get; set; }
        public string designenginename { get; set; }
        public string designengineaddr { get; set; }
        public string designgoodsname { get; set; }
        public string designgoodstype { get; set; }
        public string designtechnologyrequest { get; set; }
        public Nullable<System.DateTime> designcompletedate { get; set; }
        public Nullable<System.DateTime> designapplicationdate { get; set; }
        public string designlinkname { get; set; }
        public string designlinktel { get; set; }
        public string designemail { get; set; }
        public string state { get; set; }
        public Nullable<bool> ispay { get; set; }
        public Nullable<System.DateTime> operatetime { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
    }
}
