//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class expertsproofinfo
    {
        public string GUID { get; set; }
        public string userid { get; set; }
        public string proofcompanyname { get; set; }
        public string proofcompanyaddr { get; set; }
        public string proofnenginename { get; set; }
        public string proofnengineaddr { get; set; }
        public string proofdesigncompany { get; set; }
        public string proofgoodsname { get; set; }
        public string proofgoodstype { get; set; }
        public string prooftype { get; set; }
        public Nullable<System.DateTime> proofplandate { get; set; }
        public Nullable<System.DateTime> proofapplicationdate { get; set; }
        public string prooflinkname { get; set; }
        public string prooflinktel { get; set; }
        public string proofemail { get; set; }
        public string state { get; set; }
        public Nullable<bool> ispay { get; set; }
        public Nullable<System.DateTime> operatetime { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
    }
}
