//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class fault
    {
        public string faultid { get; set; }
        public string faulttitle { get; set; }
        public bool faultislogo { get; set; }
        public string faultlogo { get; set; }
        public System.DateTime faultdate { get; set; }
        public string faultsummary { get; set; }
        public string faultcontent { get; set; }
        public string type1 { get; set; }
        public string type2 { get; set; }
    }
}
