//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods
    {
        public string goodsid { get; set; }
        public string goodsname { get; set; }
        public string goodslogo { get; set; }
        public double goodsprice { get; set; }
        public double goodsdiscountprice { get; set; }
        public string goodstype { get; set; }
        public int goodscount { get; set; }
        public string goodscontent { get; set; }
        public Nullable<int> clickcount { get; set; }
        public Nullable<int> buycount { get; set; }
        public string goodsPinPai { get; set; }
        public string goodsType2 { get; set; }
    }
}
