//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class newstype
    {
        public string typeid { get; set; }
        public string typename { get; set; }
        public string typelogo { get; set; }
        public int sort { get; set; }
        public bool Isshow { get; set; }
        public string description { get; set; }
    }
}
