//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public string orderid { get; set; }
        public string userid { get; set; }
        public string addrid { get; set; }
        public string ordernumber { get; set; }
        public string ordertype { get; set; }
        public string orderstruts { get; set; }
        public double ordercountprice { get; set; }
        public string orderall { get; set; }
        public double orderuserdiscount { get; set; }
        public System.DateTime orderdate { get; set; }
        public string expresscompanyid { get; set; }
        public string expresscompanyname { get; set; }
        public string ordersendgoodsexpressnumber { get; set; }
        public string orderrejectgoodsexpresscompanyid { get; set; }
        public string orderrejectgoodsexpresscompanyname { get; set; }
        public string orderrejectgoodsexpressnumber { get; set; }
        public string orderrejectgoodsremark { get; set; }
        public Nullable<int> orderistytuikuan { get; set; }
        public string ordertuikuanliyou { get; set; }
        public double usepoints { get; set; }
        public Nullable<double> yunfei { get; set; }
    }
}
