//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordergoods
    {
        public string guid { get; set; }
        public string orderid { get; set; }
        public string ordergoodsid { get; set; }
        public string ordergoodslogo { get; set; }
        public string ordergoodsname { get; set; }
        public double ordergoodsprice { get; set; }
        public double ordergoodsdiscountprice { get; set; }
        public int ordergoodssize { get; set; }
        public double ordergoodscountprice { get; set; }
    }
}
