//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class testing
    {
        public string GUID { get; set; }
        public string userid { get; set; }
        public string testingclientcompanyname { get; set; }
        public string testingclientcompanyaddr { get; set; }
        public string testinglinkname { get; set; }
        public string testingtel { get; set; }
        public string testingengineeringname { get; set; }
        public string testingengineeringaddr { get; set; }
        public string testingbuildercompany { get; set; }
        public string testingconstructioncompany { get; set; }
        public string testingcontent { get; set; }
        public Nullable<int> testingsize { get; set; }
        public string testingepitome { get; set; }
        public string testingmanufacturer { get; set; }
        public string testingequipmentnumber { get; set; }
        public string testingequipmenttype { get; set; }
        public string testingmountheight { get; set; }
        public string testingother { get; set; }
        public string testingtheway { get; set; }
        public string testingmailing { get; set; }
        public string state { get; set; }
        public Nullable<bool> ispay { get; set; }
        public Nullable<System.DateTime> operatetime { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
    }
}
