//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class train
    {
        public string GUID { get; set; }
        public string userid { get; set; }
        public string trainname { get; set; }
        public string trainsex { get; set; }
        public string trainculturaldegree { get; set; }
        public Nullable<System.DateTime> trainbirthdate { get; set; }
        public string trainservicelength { get; set; }
        public string trainphysicalcondition { get; set; }
        public string traintypeid { get; set; }
        public string trainID { get; set; }
        public string traincompany { get; set; }
        public string trainpostcode { get; set; }
        public string traincompanyaddr { get; set; }
        public string trainlinkname { get; set; }
        public string traintel { get; set; }
        public string trainemail { get; set; }
        public string state { get; set; }
        public Nullable<bool> ispay { get; set; }
        public Nullable<System.DateTime> operatetime { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
    }
}
