//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string userid { get; set; }
        public string userlogo { get; set; }
        public string username { get; set; }
        public string usernickname { get; set; }
        public string userphone { get; set; }
        public string usersex { get; set; }
        public int userpoints { get; set; }
        public double userconsumption { get; set; }
        public string password { get; set; }
        public string addrid { get; set; }
        public string gradeid { get; set; }
        public string remark { get; set; }
        public string openid { get; set; }
        public string type { get; set; }
        public bool ishuanxin { get; set; }
        public string hxpassword { get; set; }
    }
}
