function test(){
	if($("#gcname").val()==""){
		alert("工程名称不能为空");
		$("#gcname").focus();
	}else{
		if($("#sgaddress").val()==""){
			alert("施工地点不能为空");
			$("#sgaddress").focus();
		}else{
			if($("#sycompany").val()==""){
				alert("使用单位不能为空");
				$("#sycompany").focus();
			}else{
				if($("#jlcompany").val()==""){
					alert("监理单位不能为空");
					$("#jlcompany").focus();
				}else{
					if($("#sbname").val()==""){
						alert("设备名称不能为空");
						$("#sbname").focus();
					}else{
						if($("#azcompany").val()==""){
							alert("安装单位不能为空");
							$("#azcompany").focus();
						}else{
							if($("#type").val()==""){
								alert("设备型号不能为空");
								$("#type").focus();
							}else{
								if($("#sbcode").val()==""){
									alert("设备编号不能为空");
									$("#sbcode").focus();
								}else{
									if($("#scstore").val()==""){
										alert("生产厂家不能为空");
										$("#scstore").focus();
									}else{
										if($("#aqscode").val()==""){
											alert("安全锁编号不能为空");
											$("#aqscode").focus();
										}else{
											if($("#xkz").val()==""){
												alert("特种设备生产制造许可证不能为空");
												$("#xkz").focus();
											}else{
												if($("#cqcode").val()==""){
													alert("产权编号不能为空");
													$("#cqcode").focus();
												}else{
													if($("#ccdate").val()==""){
														alert("出厂日期不能为空");
														$("#ccdate").focus();
													}else{
														if($("#checkheight").val()==""){
															alert("检验高度不能为空");
															$("#checkheight").focus();
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
